### PR TITLE
Task Completed

### PR DESCRIPTION
**Pull request by PriyankaPawar23**

### CODE REVIEW

**Comment by wideclassrooms** [comment]
Thank you for your submission! We really appreciate it.  Please add screenshot of the view in the project directory and send pull request again

**Comment by PriyankaPawar23** [comment]
Ok Sure

**Comment by wideclassrooms** [comment]
Thank you for your quick reply. Please send pull request again when you add the screenshot

**Comment by wideclassrooms** [comment]
Screenshot 2021-04-16 at 5 49 26 PM

error: resource color/lightblue (aka com.android.internshipprogram:color/lightblue) not found.

Please send another pull request and reply the pull request number here so your code will be checked on priority.

**Comment by PriyankaPawar23** [comment]
Please check #37 pull request

**Comment by wideclassrooms** [comment]
Got it. Good work @PriyankaPawar23

**Pull request closed without merging**
