### PR TITLE
sample project

### PR DESCRIPTION
**Pull request by Sahil-creater**
this is improved code

### CODE REVIEW

**Comment by wideclassrooms** [comment]
Your submission was good. Kindly let us know about your group so you can be added to next round of evaluation.

**Comment by Sahil-creater** [comment]
Group     D
Name     Sahil Verma
Gmail     ***@***.***

**Comment by wideclassrooms** [comment]
Congratulations.
Your change have been accepted and merged in main branch for next round of evaluation.

**Comment by Sahil-creater** [comment]
Thanks

**Pull request closed without merging**
