### PR TITLE
C group adi0515sharma

### PR DESCRIPTION
**Pull request by adi0515sharma**
Completed my designing with some changes

### CODE REVIEW

**Comment by wideclassrooms** [comment]
Your submission was good kindly resolve issues. 
Screenshot 2021-04-16 at 9 11 47 PM

**Comment by adi0515sharma** [comment]
hello sir i have solved my error "C5BEB0" solved you can run the program
https://github.com/adi0515sharma/AndroidAppDevelopers-2021/tree/c-group-adi0515sharma

**Comment by wideclassrooms** [comment]
Send me pull request and possibly send me pull request no

**Comment by adi0515sharma** [comment]
Sir i sended pull request so early.
You can see it.
Pull no :- 74

**Pull request closed without merging**
